#!/usr/bin/env sh

##############################################################################
##
##  Gradle start up script for POSIX generated by Gradle.
##
##############################################################################

APP_BASE_NAME=$(basename "$0")

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this daemon.
DEFAULT_JVM_OPTS=""

# Use the maximum available, or set MAX_FD="" for no limit.
MAX_FD="maximum"

warn() {
    echo "WARNING: $*"
}

die() {
    echo "ERROR: $*"
    exit 1
}

# OS specific support (sh and bash). Please note that in this environment, the shell is not POSIX strict.
cygwin=false
case "$(uname)" in
  CYGWIN*|MINGW*|MSYS*)
    cygwin=true
    ;;
esac

# Determine the Java command to use.
if [ -n "$JAVA_HOME" ] ; then
    JAVACMD="$JAVA_HOME/bin/java"
else
    JAVACMD="java"
fi

if [ ! -x "$JAVACMD" ] ; then
    die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
fi

# Determine the current directory and app home.
APP_HOME=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Set GRADLE_OPTS.
GRADLE_OPTS="${GRADLE_OPTS:-} -Dorg.gradle.appname=$APP_BASE_NAME"

exec "$JAVACMD" $DEFAULT_JVM_OPTS $GRADLE_OPTS -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
